#!/bin/bash

echo "PHP-FPM variables performances tuning:"
echo " - listening on ${LISTEN} as www-data:www-data with mode 0660"
echo " - max children: ${MAX_CHILDREN}"
echo " - start servers: ${START_SERVER}"
echo " - min spare servers: ${MIN_SPARE_SERVERS}"
echo " - max spare servers: ${MAX_SPARE_SERVERS}"
echo " - max requests: ${MAX_REQUESTS}"
echo " - max upload size: ${MAX_UPLOAD_SIZE}"

#
# Supervisord
#
echo "Starting supervisord for NGINX and PHP-FPM..."
supervisord -n -c /etc/supervisor/supervisord.conf